name: CI

# Runs CI for pull requests and pushes to main
on:
  pull_request:
  push:
    branches:
      - main
  # schedule:
  #   - cron: 0 14 * * MON-FRI # Every weekday at 14:00 UTC

permissions: {}

jobs:
  # Check that binary can be built
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        go-version: [1.23.x]
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        persist-credentials: false
    - name: Install Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install dependencies
      run: go mod download
    - name: Build
      run: go build -v -o /dev/null
  nix-build:
    name: Nix Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@0af51e37404acfb298f7e2eec77470be27eb57c5 # v10
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@21a544727d0c62386e78b4befe52d19ad12692e3 # v17
      - name: Build
        run: nix build .
  # Run integration tests
  test:
    needs: build
    name: 'Integration Tests'
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 8
    strategy:
      matrix:
        runs_on: [ubuntu-latest, ubuntu-24.04-arm]
        os: [ubuntu, centos, arch, opensuse]
        exclude:
          - runs_on: ubuntu-24.04-arm
            os: arch
    env:
      OS_TYPE: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        persist-credentials: false
    - name: Install Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version-file: 'go.mod'
    - name: Install Docker
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3
    - name: Install dependencies
      run: go mod download
    - name: Run integration tests
      run: go test -tags=integration ./test/integration -timeout=15m -count=1 -parallel=2 -v
  lint-scripts:
    name: Shell Scripts Lint & Test
    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed
    steps:
    - name: Install packages
      run: |
        zypper refresh
        zypper --non-interactive install --no-recommends git ShellCheck shunit2 findutils python313-bashate
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        persist-credentials: false
    - name: Run ShellCheck
      run: |
        echo "Running ShellCheck on all .sh files under scripts/"
        find scripts/ -type f -name '*.sh' | while read -r file; do
          echo "üîç Checking $file"
          shellcheck "$file"
        done
    - name: Run shunit2 tests
      run: |
        echo "Running shUnit2 on all .sh files under scripts/test"
        find scripts/test -type f -name '*.sh' | while read -r file; do
          echo "üîç Checking $file"
          bash "$file"
        done
    - name: Check scripts with bashate
      run: |
        echo "Running bashate on all .sh files under scripts/"
        find scripts/ -type f -name '*.sh' | while read -r file; do
          echo "üîç Checking $file"
          bashate -i E006 "$file"
        done
